package work;

import java.util.Date;

public class AfterPayLog {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column after_pay_log.id
	 * @mbggenerated  Fri Nov 11 17:31:33 CST 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column after_pay_log.userid
	 * @mbggenerated  Fri Nov 11 17:31:33 CST 2016
	 */
	private String userid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column after_pay_log.orderid
	 * @mbggenerated  Fri Nov 11 17:31:33 CST 2016
	 */
	private String orderid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column after_pay_log.channelid
	 * @mbggenerated  Fri Nov 11 17:31:33 CST 2016
	 */
	private String channelid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column after_pay_log.fm
	 * @mbggenerated  Fri Nov 11 17:31:33 CST 2016
	 */
	private String fm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column after_pay_log.error_code
	 * @mbggenerated  Fri Nov 11 17:31:33 CST 2016
	 */
	private String errorCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column after_pay_log.create_time
	 * @mbggenerated  Fri Nov 11 17:31:33 CST 2016
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column after_pay_log.appid
	 * @mbggenerated  Fri Nov 11 17:31:33 CST 2016
	 */
	private String appid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column after_pay_log.pro
	 * @mbggenerated  Fri Nov 11 17:31:33 CST 2016
	 */
	private String pro;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column after_pay_log.id
	 * @return  the value of after_pay_log.id
	 * @mbggenerated  Fri Nov 11 17:31:33 CST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column after_pay_log.id
	 * @param id  the value for after_pay_log.id
	 * @mbggenerated  Fri Nov 11 17:31:33 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column after_pay_log.userid
	 * @return  the value of after_pay_log.userid
	 * @mbggenerated  Fri Nov 11 17:31:33 CST 2016
	 */
	public String getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column after_pay_log.userid
	 * @param userid  the value for after_pay_log.userid
	 * @mbggenerated  Fri Nov 11 17:31:33 CST 2016
	 */
	public void setUserid(String userid) {
		this.userid = userid == null ? null : userid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column after_pay_log.orderid
	 * @return  the value of after_pay_log.orderid
	 * @mbggenerated  Fri Nov 11 17:31:33 CST 2016
	 */
	public String getOrderid() {
		return orderid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column after_pay_log.orderid
	 * @param orderid  the value for after_pay_log.orderid
	 * @mbggenerated  Fri Nov 11 17:31:33 CST 2016
	 */
	public void setOrderid(String orderid) {
		this.orderid = orderid == null ? null : orderid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column after_pay_log.channelid
	 * @return  the value of after_pay_log.channelid
	 * @mbggenerated  Fri Nov 11 17:31:33 CST 2016
	 */
	public String getChannelid() {
		return channelid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column after_pay_log.channelid
	 * @param channelid  the value for after_pay_log.channelid
	 * @mbggenerated  Fri Nov 11 17:31:33 CST 2016
	 */
	public void setChannelid(String channelid) {
		this.channelid = channelid == null ? null : channelid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column after_pay_log.fm
	 * @return  the value of after_pay_log.fm
	 * @mbggenerated  Fri Nov 11 17:31:33 CST 2016
	 */
	public String getFm() {
		return fm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column after_pay_log.fm
	 * @param fm  the value for after_pay_log.fm
	 * @mbggenerated  Fri Nov 11 17:31:33 CST 2016
	 */
	public void setFm(String fm) {
		this.fm = fm == null ? null : fm.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column after_pay_log.error_code
	 * @return  the value of after_pay_log.error_code
	 * @mbggenerated  Fri Nov 11 17:31:33 CST 2016
	 */
	public String getErrorCode() {
		return errorCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column after_pay_log.error_code
	 * @param errorCode  the value for after_pay_log.error_code
	 * @mbggenerated  Fri Nov 11 17:31:33 CST 2016
	 */
	public void setErrorCode(String errorCode) {
		this.errorCode = errorCode == null ? null : errorCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column after_pay_log.create_time
	 * @return  the value of after_pay_log.create_time
	 * @mbggenerated  Fri Nov 11 17:31:33 CST 2016
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column after_pay_log.create_time
	 * @param createTime  the value for after_pay_log.create_time
	 * @mbggenerated  Fri Nov 11 17:31:33 CST 2016
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column after_pay_log.appid
	 * @return  the value of after_pay_log.appid
	 * @mbggenerated  Fri Nov 11 17:31:33 CST 2016
	 */
	public String getAppid() {
		return appid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column after_pay_log.appid
	 * @param appid  the value for after_pay_log.appid
	 * @mbggenerated  Fri Nov 11 17:31:33 CST 2016
	 */
	public void setAppid(String appid) {
		this.appid = appid == null ? null : appid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column after_pay_log.pro
	 * @return  the value of after_pay_log.pro
	 * @mbggenerated  Fri Nov 11 17:31:33 CST 2016
	 */
	public String getPro() {
		return pro;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column after_pay_log.pro
	 * @param pro  the value for after_pay_log.pro
	 * @mbggenerated  Fri Nov 11 17:31:33 CST 2016
	 */
	public void setPro(String pro) {
		this.pro = pro == null ? null : pro.trim();
	}
}