package work;

import java.util.Date;

public class AppInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_info.id
	 * @mbggenerated  Mon Oct 24 11:26:04 CST 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_info.app_id
	 * @mbggenerated  Mon Oct 24 11:26:04 CST 2016
	 */
	private String appId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_info.create_time
	 * @mbggenerated  Mon Oct 24 11:26:04 CST 2016
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_info.name
	 * @mbggenerated  Mon Oct 24 11:26:04 CST 2016
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_info.package_name
	 * @mbggenerated  Mon Oct 24 11:26:04 CST 2016
	 */
	private String packageName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_info.url
	 * @mbggenerated  Mon Oct 24 11:26:04 CST 2016
	 */
	private String url;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_info.bili
	 * @mbggenerated  Mon Oct 24 11:26:04 CST 2016
	 */
	private Integer bili;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_info.remark
	 * @mbggenerated  Mon Oct 24 11:26:04 CST 2016
	 */
	private String remark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_info.state
	 * @mbggenerated  Mon Oct 24 11:26:04 CST 2016
	 */
	private Integer state;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_info.id
	 * @return  the value of app_info.id
	 * @mbggenerated  Mon Oct 24 11:26:04 CST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_info.id
	 * @param id  the value for app_info.id
	 * @mbggenerated  Mon Oct 24 11:26:04 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_info.app_id
	 * @return  the value of app_info.app_id
	 * @mbggenerated  Mon Oct 24 11:26:04 CST 2016
	 */
	public String getAppId() {
		return appId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_info.app_id
	 * @param appId  the value for app_info.app_id
	 * @mbggenerated  Mon Oct 24 11:26:04 CST 2016
	 */
	public void setAppId(String appId) {
		this.appId = appId == null ? null : appId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_info.create_time
	 * @return  the value of app_info.create_time
	 * @mbggenerated  Mon Oct 24 11:26:04 CST 2016
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_info.create_time
	 * @param createTime  the value for app_info.create_time
	 * @mbggenerated  Mon Oct 24 11:26:04 CST 2016
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_info.name
	 * @return  the value of app_info.name
	 * @mbggenerated  Mon Oct 24 11:26:04 CST 2016
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_info.name
	 * @param name  the value for app_info.name
	 * @mbggenerated  Mon Oct 24 11:26:04 CST 2016
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_info.package_name
	 * @return  the value of app_info.package_name
	 * @mbggenerated  Mon Oct 24 11:26:04 CST 2016
	 */
	public String getPackageName() {
		return packageName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_info.package_name
	 * @param packageName  the value for app_info.package_name
	 * @mbggenerated  Mon Oct 24 11:26:04 CST 2016
	 */
	public void setPackageName(String packageName) {
		this.packageName = packageName == null ? null : packageName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_info.url
	 * @return  the value of app_info.url
	 * @mbggenerated  Mon Oct 24 11:26:04 CST 2016
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_info.url
	 * @param url  the value for app_info.url
	 * @mbggenerated  Mon Oct 24 11:26:04 CST 2016
	 */
	public void setUrl(String url) {
		this.url = url == null ? null : url.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_info.bili
	 * @return  the value of app_info.bili
	 * @mbggenerated  Mon Oct 24 11:26:04 CST 2016
	 */
	public Integer getBili() {
		return bili;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_info.bili
	 * @param bili  the value for app_info.bili
	 * @mbggenerated  Mon Oct 24 11:26:04 CST 2016
	 */
	public void setBili(Integer bili) {
		this.bili = bili;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_info.remark
	 * @return  the value of app_info.remark
	 * @mbggenerated  Mon Oct 24 11:26:04 CST 2016
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_info.remark
	 * @param remark  the value for app_info.remark
	 * @mbggenerated  Mon Oct 24 11:26:04 CST 2016
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_info.state
	 * @return  the value of app_info.state
	 * @mbggenerated  Mon Oct 24 11:26:04 CST 2016
	 */
	public Integer getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_info.state
	 * @param state  the value for app_info.state
	 * @mbggenerated  Mon Oct 24 11:26:04 CST 2016
	 */
	public void setState(Integer state) {
		this.state = state;
	}
}