package com.yace;

import java.util.Date;

public class Register {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column registerapp.user_id
	 * @mbggenerated  Fri Sep 23 11:05:18 CST 2016
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column registerapp.appid
	 * @mbggenerated  Fri Sep 23 11:05:18 CST 2016
	 */
	private String appid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column registerapp.imei
	 * @mbggenerated  Fri Sep 23 11:05:18 CST 2016
	 */
	private String imei;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column registerapp.iccid
	 * @mbggenerated  Fri Sep 23 11:05:18 CST 2016
	 */
	private String iccid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column registerapp.imsi
	 * @mbggenerated  Fri Sep 23 11:05:18 CST 2016
	 */
	private String imsi;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column registerapp.distro
	 * @mbggenerated  Fri Sep 23 11:05:18 CST 2016
	 */
	private String distro;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column registerapp.appver
	 * @mbggenerated  Fri Sep 23 11:05:18 CST 2016
	 */
	private String appver;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column registerapp.useragent
	 * @mbggenerated  Fri Sep 23 11:05:18 CST 2016
	 */
	private String useragent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column registerapp.model
	 * @mbggenerated  Fri Sep 23 11:05:18 CST 2016
	 */
	private String model;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column registerapp.mac
	 * @mbggenerated  Fri Sep 23 11:05:18 CST 2016
	 */
	private String mac;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column registerapp.tel
	 * @mbggenerated  Fri Sep 23 11:05:18 CST 2016
	 */
	private String tel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column registerapp.carrier
	 * @mbggenerated  Fri Sep 23 11:05:18 CST 2016
	 */
	private String carrier;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column registerapp.create_time
	 * @mbggenerated  Fri Sep 23 11:05:18 CST 2016
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column registerapp.androidversion
	 * @mbggenerated  Fri Sep 23 11:05:18 CST 2016
	 */
	private String androidversion;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column registerapp.pro
	 * @mbggenerated  Fri Sep 23 11:05:18 CST 2016
	 */
	private String pro;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column registerapp.ip
	 * @mbggenerated  Fri Sep 23 11:05:18 CST 2016
	 */
	private String ip;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column registerapp.screen
	 * @mbggenerated  Fri Sep 23 11:05:18 CST 2016
	 */
	private String screen;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column registerapp.tel_type
	 * @mbggenerated  Fri Sep 23 11:05:18 CST 2016
	 */
	private String telType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column registerapp.qxt_type
	 * @mbggenerated  Fri Sep 23 11:05:18 CST 2016
	 */
	private String qxtType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column registerapp.lac
	 * @mbggenerated  Fri Sep 23 11:05:18 CST 2016
	 */
	private String lac;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column registerapp.cid
	 * @mbggenerated  Fri Sep 23 11:05:18 CST 2016
	 */
	private String cid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column registerapp.user_id
	 * @return  the value of registerapp.user_id
	 * @mbggenerated  Fri Sep 23 11:05:18 CST 2016
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column registerapp.user_id
	 * @param userId  the value for registerapp.user_id
	 * @mbggenerated  Fri Sep 23 11:05:18 CST 2016
	 */
	public void setUserId(String userId) {
		this.userId = userId == null ? null : userId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column registerapp.appid
	 * @return  the value of registerapp.appid
	 * @mbggenerated  Fri Sep 23 11:05:18 CST 2016
	 */
	public String getAppid() {
		return appid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column registerapp.appid
	 * @param appid  the value for registerapp.appid
	 * @mbggenerated  Fri Sep 23 11:05:18 CST 2016
	 */
	public void setAppid(String appid) {
		this.appid = appid == null ? null : appid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column registerapp.imei
	 * @return  the value of registerapp.imei
	 * @mbggenerated  Fri Sep 23 11:05:18 CST 2016
	 */
	public String getImei() {
		return imei;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column registerapp.imei
	 * @param imei  the value for registerapp.imei
	 * @mbggenerated  Fri Sep 23 11:05:18 CST 2016
	 */
	public void setImei(String imei) {
		this.imei = imei == null ? null : imei.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column registerapp.iccid
	 * @return  the value of registerapp.iccid
	 * @mbggenerated  Fri Sep 23 11:05:18 CST 2016
	 */
	public String getIccid() {
		return iccid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column registerapp.iccid
	 * @param iccid  the value for registerapp.iccid
	 * @mbggenerated  Fri Sep 23 11:05:18 CST 2016
	 */
	public void setIccid(String iccid) {
		this.iccid = iccid == null ? null : iccid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column registerapp.imsi
	 * @return  the value of registerapp.imsi
	 * @mbggenerated  Fri Sep 23 11:05:18 CST 2016
	 */
	public String getImsi() {
		return imsi;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column registerapp.imsi
	 * @param imsi  the value for registerapp.imsi
	 * @mbggenerated  Fri Sep 23 11:05:18 CST 2016
	 */
	public void setImsi(String imsi) {
		this.imsi = imsi == null ? null : imsi.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column registerapp.distro
	 * @return  the value of registerapp.distro
	 * @mbggenerated  Fri Sep 23 11:05:18 CST 2016
	 */
	public String getDistro() {
		return distro;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column registerapp.distro
	 * @param distro  the value for registerapp.distro
	 * @mbggenerated  Fri Sep 23 11:05:18 CST 2016
	 */
	public void setDistro(String distro) {
		this.distro = distro == null ? null : distro.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column registerapp.appver
	 * @return  the value of registerapp.appver
	 * @mbggenerated  Fri Sep 23 11:05:18 CST 2016
	 */
	public String getAppver() {
		return appver;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column registerapp.appver
	 * @param appver  the value for registerapp.appver
	 * @mbggenerated  Fri Sep 23 11:05:18 CST 2016
	 */
	public void setAppver(String appver) {
		this.appver = appver == null ? null : appver.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column registerapp.useragent
	 * @return  the value of registerapp.useragent
	 * @mbggenerated  Fri Sep 23 11:05:18 CST 2016
	 */
	public String getUseragent() {
		return useragent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column registerapp.useragent
	 * @param useragent  the value for registerapp.useragent
	 * @mbggenerated  Fri Sep 23 11:05:18 CST 2016
	 */
	public void setUseragent(String useragent) {
		this.useragent = useragent == null ? null : useragent.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column registerapp.model
	 * @return  the value of registerapp.model
	 * @mbggenerated  Fri Sep 23 11:05:18 CST 2016
	 */
	public String getModel() {
		return model;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column registerapp.model
	 * @param model  the value for registerapp.model
	 * @mbggenerated  Fri Sep 23 11:05:18 CST 2016
	 */
	public void setModel(String model) {
		this.model = model == null ? null : model.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column registerapp.mac
	 * @return  the value of registerapp.mac
	 * @mbggenerated  Fri Sep 23 11:05:18 CST 2016
	 */
	public String getMac() {
		return mac;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column registerapp.mac
	 * @param mac  the value for registerapp.mac
	 * @mbggenerated  Fri Sep 23 11:05:18 CST 2016
	 */
	public void setMac(String mac) {
		this.mac = mac == null ? null : mac.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column registerapp.tel
	 * @return  the value of registerapp.tel
	 * @mbggenerated  Fri Sep 23 11:05:18 CST 2016
	 */
	public String getTel() {
		return tel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column registerapp.tel
	 * @param tel  the value for registerapp.tel
	 * @mbggenerated  Fri Sep 23 11:05:18 CST 2016
	 */
	public void setTel(String tel) {
		this.tel = tel == null ? null : tel.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column registerapp.carrier
	 * @return  the value of registerapp.carrier
	 * @mbggenerated  Fri Sep 23 11:05:18 CST 2016
	 */
	public String getCarrier() {
		return carrier;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column registerapp.carrier
	 * @param carrier  the value for registerapp.carrier
	 * @mbggenerated  Fri Sep 23 11:05:18 CST 2016
	 */
	public void setCarrier(String carrier) {
		this.carrier = carrier == null ? null : carrier.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column registerapp.create_time
	 * @return  the value of registerapp.create_time
	 * @mbggenerated  Fri Sep 23 11:05:18 CST 2016
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column registerapp.create_time
	 * @param createTime  the value for registerapp.create_time
	 * @mbggenerated  Fri Sep 23 11:05:18 CST 2016
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column registerapp.androidversion
	 * @return  the value of registerapp.androidversion
	 * @mbggenerated  Fri Sep 23 11:05:18 CST 2016
	 */
	public String getAndroidversion() {
		return androidversion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column registerapp.androidversion
	 * @param androidversion  the value for registerapp.androidversion
	 * @mbggenerated  Fri Sep 23 11:05:18 CST 2016
	 */
	public void setAndroidversion(String androidversion) {
		this.androidversion = androidversion == null ? null : androidversion
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column registerapp.pro
	 * @return  the value of registerapp.pro
	 * @mbggenerated  Fri Sep 23 11:05:18 CST 2016
	 */
	public String getPro() {
		return pro;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column registerapp.pro
	 * @param pro  the value for registerapp.pro
	 * @mbggenerated  Fri Sep 23 11:05:18 CST 2016
	 */
	public void setPro(String pro) {
		this.pro = pro == null ? null : pro.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column registerapp.ip
	 * @return  the value of registerapp.ip
	 * @mbggenerated  Fri Sep 23 11:05:18 CST 2016
	 */
	public String getIp() {
		return ip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column registerapp.ip
	 * @param ip  the value for registerapp.ip
	 * @mbggenerated  Fri Sep 23 11:05:18 CST 2016
	 */
	public void setIp(String ip) {
		this.ip = ip == null ? null : ip.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column registerapp.screen
	 * @return  the value of registerapp.screen
	 * @mbggenerated  Fri Sep 23 11:05:18 CST 2016
	 */
	public String getScreen() {
		return screen;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column registerapp.screen
	 * @param screen  the value for registerapp.screen
	 * @mbggenerated  Fri Sep 23 11:05:18 CST 2016
	 */
	public void setScreen(String screen) {
		this.screen = screen == null ? null : screen.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column registerapp.tel_type
	 * @return  the value of registerapp.tel_type
	 * @mbggenerated  Fri Sep 23 11:05:18 CST 2016
	 */
	public String getTelType() {
		return telType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column registerapp.tel_type
	 * @param telType  the value for registerapp.tel_type
	 * @mbggenerated  Fri Sep 23 11:05:18 CST 2016
	 */
	public void setTelType(String telType) {
		this.telType = telType == null ? null : telType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column registerapp.qxt_type
	 * @return  the value of registerapp.qxt_type
	 * @mbggenerated  Fri Sep 23 11:05:18 CST 2016
	 */
	public String getQxtType() {
		return qxtType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column registerapp.qxt_type
	 * @param qxtType  the value for registerapp.qxt_type
	 * @mbggenerated  Fri Sep 23 11:05:18 CST 2016
	 */
	public void setQxtType(String qxtType) {
		this.qxtType = qxtType == null ? null : qxtType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column registerapp.lac
	 * @return  the value of registerapp.lac
	 * @mbggenerated  Fri Sep 23 11:05:18 CST 2016
	 */
	public String getLac() {
		return lac;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column registerapp.lac
	 * @param lac  the value for registerapp.lac
	 * @mbggenerated  Fri Sep 23 11:05:18 CST 2016
	 */
	public void setLac(String lac) {
		this.lac = lac == null ? null : lac.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column registerapp.cid
	 * @return  the value of registerapp.cid
	 * @mbggenerated  Fri Sep 23 11:05:18 CST 2016
	 */
	public String getCid() {
		return cid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column registerapp.cid
	 * @param cid  the value for registerapp.cid
	 * @mbggenerated  Fri Sep 23 11:05:18 CST 2016
	 */
	public void setCid(String cid) {
		this.cid = cid == null ? null : cid.trim();
	}
}