/* DO NOT EDIT THIS FILE - it is machine generated */
#include <C:\\java\\jdk1.8\\include\\jni.h>
/* Header for class WinMsgBox */

#ifndef _Included_WinMsgBox
#define _Included_WinMsgBox
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     WinMsgBox
 * Method:    showMsgBox
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_WinMsgBox_showMsgBox
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
