package com.monitor;

import java.util.Date;

public class ReqcontentDb {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reqcontent_db.id
	 * @mbggenerated  Mon Nov 21 17:52:15 CST 2016
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reqcontent_db.create_time
	 * @mbggenerated  Mon Nov 21 17:52:15 CST 2016
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reqcontent_db.imei
	 * @mbggenerated  Mon Nov 21 17:52:15 CST 2016
	 */
	private String imei;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reqcontent_db.imsi
	 * @mbggenerated  Mon Nov 21 17:52:15 CST 2016
	 */
	private String imsi;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reqcontent_db.fm
	 * @mbggenerated  Mon Nov 21 17:52:15 CST 2016
	 */
	private String fm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reqcontent_db.paycode
	 * @mbggenerated  Mon Nov 21 17:52:15 CST 2016
	 */
	private String paycode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reqcontent_db.channel
	 * @mbggenerated  Mon Nov 21 17:52:15 CST 2016
	 */
	private String channel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reqcontent_db.userdata
	 * @mbggenerated  Mon Nov 21 17:52:15 CST 2016
	 */
	private String userdata;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reqcontent_db.bieming
	 * @mbggenerated  Mon Nov 21 17:52:15 CST 2016
	 */
	private String bieming;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reqcontent_db.orderid
	 * @mbggenerated  Mon Nov 21 17:52:15 CST 2016
	 */
	private String orderid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reqcontent_db.result
	 * @mbggenerated  Mon Nov 21 17:52:15 CST 2016
	 */
	private Byte result;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reqcontent_db.app_serial_no
	 * @mbggenerated  Mon Nov 21 17:52:15 CST 2016
	 */
	private String appSerialNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reqcontent_db.pro
	 * @mbggenerated  Mon Nov 21 17:52:15 CST 2016
	 */
	private String pro;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reqcontent_db.price
	 * @mbggenerated  Mon Nov 21 17:52:15 CST 2016
	 */
	private Integer price;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reqcontent_db.carrier
	 * @mbggenerated  Mon Nov 21 17:52:15 CST 2016
	 */
	private String carrier;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reqcontent_db.mobile
	 * @mbggenerated  Mon Nov 21 17:52:15 CST 2016
	 */
	private String mobile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reqcontent_db.vcode
	 * @mbggenerated  Mon Nov 21 17:52:15 CST 2016
	 */
	private String vcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reqcontent_db.appid
	 * @mbggenerated  Mon Nov 21 17:52:15 CST 2016
	 */
	private String appid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reqcontent_db.req_price
	 * @mbggenerated  Mon Nov 21 17:52:15 CST 2016
	 */
	private Integer reqPrice;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reqcontent_db.id
	 * @return  the value of reqcontent_db.id
	 * @mbggenerated  Mon Nov 21 17:52:15 CST 2016
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reqcontent_db.id
	 * @param id  the value for reqcontent_db.id
	 * @mbggenerated  Mon Nov 21 17:52:15 CST 2016
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reqcontent_db.create_time
	 * @return  the value of reqcontent_db.create_time
	 * @mbggenerated  Mon Nov 21 17:52:15 CST 2016
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reqcontent_db.create_time
	 * @param createTime  the value for reqcontent_db.create_time
	 * @mbggenerated  Mon Nov 21 17:52:15 CST 2016
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reqcontent_db.imei
	 * @return  the value of reqcontent_db.imei
	 * @mbggenerated  Mon Nov 21 17:52:15 CST 2016
	 */
	public String getImei() {
		return imei;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reqcontent_db.imei
	 * @param imei  the value for reqcontent_db.imei
	 * @mbggenerated  Mon Nov 21 17:52:15 CST 2016
	 */
	public void setImei(String imei) {
		this.imei = imei == null ? null : imei.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reqcontent_db.imsi
	 * @return  the value of reqcontent_db.imsi
	 * @mbggenerated  Mon Nov 21 17:52:15 CST 2016
	 */
	public String getImsi() {
		return imsi;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reqcontent_db.imsi
	 * @param imsi  the value for reqcontent_db.imsi
	 * @mbggenerated  Mon Nov 21 17:52:15 CST 2016
	 */
	public void setImsi(String imsi) {
		this.imsi = imsi == null ? null : imsi.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reqcontent_db.fm
	 * @return  the value of reqcontent_db.fm
	 * @mbggenerated  Mon Nov 21 17:52:15 CST 2016
	 */
	public String getFm() {
		return fm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reqcontent_db.fm
	 * @param fm  the value for reqcontent_db.fm
	 * @mbggenerated  Mon Nov 21 17:52:15 CST 2016
	 */
	public void setFm(String fm) {
		this.fm = fm == null ? null : fm.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reqcontent_db.paycode
	 * @return  the value of reqcontent_db.paycode
	 * @mbggenerated  Mon Nov 21 17:52:15 CST 2016
	 */
	public String getPaycode() {
		return paycode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reqcontent_db.paycode
	 * @param paycode  the value for reqcontent_db.paycode
	 * @mbggenerated  Mon Nov 21 17:52:15 CST 2016
	 */
	public void setPaycode(String paycode) {
		this.paycode = paycode == null ? null : paycode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reqcontent_db.channel
	 * @return  the value of reqcontent_db.channel
	 * @mbggenerated  Mon Nov 21 17:52:15 CST 2016
	 */
	public String getChannel() {
		return channel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reqcontent_db.channel
	 * @param channel  the value for reqcontent_db.channel
	 * @mbggenerated  Mon Nov 21 17:52:15 CST 2016
	 */
	public void setChannel(String channel) {
		this.channel = channel == null ? null : channel.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reqcontent_db.userdata
	 * @return  the value of reqcontent_db.userdata
	 * @mbggenerated  Mon Nov 21 17:52:15 CST 2016
	 */
	public String getUserdata() {
		return userdata;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reqcontent_db.userdata
	 * @param userdata  the value for reqcontent_db.userdata
	 * @mbggenerated  Mon Nov 21 17:52:15 CST 2016
	 */
	public void setUserdata(String userdata) {
		this.userdata = userdata == null ? null : userdata.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reqcontent_db.bieming
	 * @return  the value of reqcontent_db.bieming
	 * @mbggenerated  Mon Nov 21 17:52:15 CST 2016
	 */
	public String getBieming() {
		return bieming;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reqcontent_db.bieming
	 * @param bieming  the value for reqcontent_db.bieming
	 * @mbggenerated  Mon Nov 21 17:52:15 CST 2016
	 */
	public void setBieming(String bieming) {
		this.bieming = bieming == null ? null : bieming.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reqcontent_db.orderid
	 * @return  the value of reqcontent_db.orderid
	 * @mbggenerated  Mon Nov 21 17:52:15 CST 2016
	 */
	public String getOrderid() {
		return orderid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reqcontent_db.orderid
	 * @param orderid  the value for reqcontent_db.orderid
	 * @mbggenerated  Mon Nov 21 17:52:15 CST 2016
	 */
	public void setOrderid(String orderid) {
		this.orderid = orderid == null ? null : orderid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reqcontent_db.result
	 * @return  the value of reqcontent_db.result
	 * @mbggenerated  Mon Nov 21 17:52:15 CST 2016
	 */
	public Byte getResult() {
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reqcontent_db.result
	 * @param result  the value for reqcontent_db.result
	 * @mbggenerated  Mon Nov 21 17:52:15 CST 2016
	 */
	public void setResult(Byte result) {
		this.result = result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reqcontent_db.app_serial_no
	 * @return  the value of reqcontent_db.app_serial_no
	 * @mbggenerated  Mon Nov 21 17:52:15 CST 2016
	 */
	public String getAppSerialNo() {
		return appSerialNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reqcontent_db.app_serial_no
	 * @param appSerialNo  the value for reqcontent_db.app_serial_no
	 * @mbggenerated  Mon Nov 21 17:52:15 CST 2016
	 */
	public void setAppSerialNo(String appSerialNo) {
		this.appSerialNo = appSerialNo == null ? null : appSerialNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reqcontent_db.pro
	 * @return  the value of reqcontent_db.pro
	 * @mbggenerated  Mon Nov 21 17:52:15 CST 2016
	 */
	public String getPro() {
		return pro;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reqcontent_db.pro
	 * @param pro  the value for reqcontent_db.pro
	 * @mbggenerated  Mon Nov 21 17:52:15 CST 2016
	 */
	public void setPro(String pro) {
		this.pro = pro == null ? null : pro.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reqcontent_db.price
	 * @return  the value of reqcontent_db.price
	 * @mbggenerated  Mon Nov 21 17:52:15 CST 2016
	 */
	public Integer getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reqcontent_db.price
	 * @param price  the value for reqcontent_db.price
	 * @mbggenerated  Mon Nov 21 17:52:15 CST 2016
	 */
	public void setPrice(Integer price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reqcontent_db.carrier
	 * @return  the value of reqcontent_db.carrier
	 * @mbggenerated  Mon Nov 21 17:52:15 CST 2016
	 */
	public String getCarrier() {
		return carrier;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reqcontent_db.carrier
	 * @param carrier  the value for reqcontent_db.carrier
	 * @mbggenerated  Mon Nov 21 17:52:15 CST 2016
	 */
	public void setCarrier(String carrier) {
		this.carrier = carrier == null ? null : carrier.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reqcontent_db.mobile
	 * @return  the value of reqcontent_db.mobile
	 * @mbggenerated  Mon Nov 21 17:52:15 CST 2016
	 */
	public String getMobile() {
		return mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reqcontent_db.mobile
	 * @param mobile  the value for reqcontent_db.mobile
	 * @mbggenerated  Mon Nov 21 17:52:15 CST 2016
	 */
	public void setMobile(String mobile) {
		this.mobile = mobile == null ? null : mobile.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reqcontent_db.vcode
	 * @return  the value of reqcontent_db.vcode
	 * @mbggenerated  Mon Nov 21 17:52:15 CST 2016
	 */
	public String getVcode() {
		return vcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reqcontent_db.vcode
	 * @param vcode  the value for reqcontent_db.vcode
	 * @mbggenerated  Mon Nov 21 17:52:15 CST 2016
	 */
	public void setVcode(String vcode) {
		this.vcode = vcode == null ? null : vcode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reqcontent_db.appid
	 * @return  the value of reqcontent_db.appid
	 * @mbggenerated  Mon Nov 21 17:52:15 CST 2016
	 */
	public String getAppid() {
		return appid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reqcontent_db.appid
	 * @param appid  the value for reqcontent_db.appid
	 * @mbggenerated  Mon Nov 21 17:52:15 CST 2016
	 */
	public void setAppid(String appid) {
		this.appid = appid == null ? null : appid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reqcontent_db.req_price
	 * @return  the value of reqcontent_db.req_price
	 * @mbggenerated  Mon Nov 21 17:52:15 CST 2016
	 */
	public Integer getReqPrice() {
		return reqPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reqcontent_db.req_price
	 * @param reqPrice  the value for reqcontent_db.req_price
	 * @mbggenerated  Mon Nov 21 17:52:15 CST 2016
	 */
	public void setReqPrice(Integer reqPrice) {
		this.reqPrice = reqPrice;
	}

	@Override
	public String toString() {
		return "ReqcontentDb [id=" + id + ", channel=" + channel + ", appid="
				+ appid + "]";
	}


}